package com.aiawareness.diary.ui.screens

import com.aiawareness.diary.data.model.Record
import java.time.LocalDate
import java.time.format.DateTimeFormatter

enum class HomeRecordIcon { Breath, Air, Rest, Heart, Reflection }
enum class HomeAiEntryAction { ShowRecordHint, ShowAiConfigHint, GenerateDiary, None }
enum class HomePhotoEntryMode { ActionSheet }

private val homeRecordDateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd")
private val homeRecordBadgeFormatter = DateTimeFormatter.ofPattern("M月d日")
private val homeRecordWeekdays = listOf("周一", "周二", "周三", "周四", "周五", "周六", "周日")

fun progressDots(@Suppress("UNUSED_PARAMETER") recordCount: Int): List<Boolean> {
    return emptyList()
}

fun homeEmptyStateTitle(): String = "今天的觉察，还没开始"

fun homeEmptyStateBody(): String =
    "从一个很小的当下开始，写下此刻的呼吸、身体感觉，或刚刚闪过的念头。"

fun homeEmptyStateShowsIcon(): Boolean = false

fun homePendingPhotoShowsLabels(): Boolean = false

fun homeEmptyStateUsesAlternateSurface(): Boolean = true

fun homePhotoEntryMode(): HomePhotoEntryMode = HomePhotoEntryMode.ActionSheet

fun homePhotoSheetPickLabel(): String = "从相册选择"

fun homePhotoSheetCaptureLabel(): String = "拍照"

fun homePhotoCaptureFailureMessage(): String = "拍照失败，请重试"

fun homePhotoNoCameraMessage(): String = "未找到可用相机"

fun homeHeadlineDate(date: String): String = homeRecordDateBadge(date)

fun homeRecordShowsPhoto(record: Record): Boolean = record.photoPath.isNotBlank()

fun homeAiEntryButtonLabel(
    recordCount: Int,
    hasApiKey: Boolean,
    hasDiary: Boolean,
    isGenerating: Boolean
): String = when {
    isGenerating -> "生成中..."
    recordCount == 0 -> "先记录，再生成 AI 日记"
    !hasApiKey -> "先配置 AI"
    hasDiary -> "重新生成"
    else -> "生成 AI 日记"
}

fun homeAiEntryAction(
    recordCount: Int,
    hasApiKey: Boolean,
    isGenerating: Boolean
): HomeAiEntryAction = when {
    isGenerating -> HomeAiEntryAction.None
    recordCount == 0 -> HomeAiEntryAction.ShowRecordHint
    !hasApiKey -> HomeAiEntryAction.ShowAiConfigHint
    else -> HomeAiEntryAction.GenerateDiary
}

fun homeAiEntryHint(hasApiKey: Boolean): String? =
    homeAiEntryHint(
        hasApiKey = hasApiKey,
        catchUpGeneratedCount = 0,
        todayAutoGenerated = false,
        autoGenerationFailed = false
    )

fun homeAiConfigRequiredSnackbarMessage(): String = "可一键生成AI日记，请先前往设置中完成 AI配置"

fun homeAiEntryHint(hasApiKey: Boolean, autoGenerationFailed: Boolean): String? =
    homeAiEntryHint(
        hasApiKey = hasApiKey,
        catchUpGeneratedCount = 0,
        todayAutoGenerated = false,
        autoGenerationFailed = autoGenerationFailed
    )

fun homeAiEntryHint(
    hasApiKey: Boolean,
    catchUpGeneratedCount: Int,
    todayAutoGenerated: Boolean,
    autoGenerationFailed: Boolean
): String? = when {
    autoGenerationFailed -> "AI 日记生成失败，请检查账号、网络状态、连接配置等"
    catchUpGeneratedCount > 0 -> "已补生成 ${catchUpGeneratedCount} 篇 AI 日记，可前往回顾查看"
    todayAutoGenerated -> "今日 AI 日记已自动生成，可前往回顾查看"
    hasApiKey -> null
    else -> "请前往配置 AI 和每日自动生成 AI 日记时间"
}

fun homeAutoGenerationSnackbarHint(
    catchUpGeneratedCount: Int,
    todayAutoGenerated: Boolean,
    autoGenerationFailed: Boolean
): String? = when {
    autoGenerationFailed -> "AI 日记生成失败，请检查账号、网络状态、连接配置等"
    catchUpGeneratedCount > 0 -> "已补生成 ${catchUpGeneratedCount} 篇 AI 日记，可前往回顾查看"
    todayAutoGenerated -> "今日 AI 日记已自动生成，可前往回顾查看"
    else -> null
}

fun homeAiSnackbarMessage(
    generatedDiaryReadyDate: String?,
    inlineHint: String?,
    autoGenerationHint: String?
): String? = when {
    generatedDiaryReadyDate != null -> "AI 日记已生成，可前往回顾页查看"
    inlineHint != null -> inlineHint
    else -> autoGenerationHint
}

fun homeRecordDateBadge(date: String): String {
    val localDate = LocalDate.parse(date, homeRecordDateFormatter)
    return "${localDate.format(homeRecordBadgeFormatter)} ${homeRecordWeekdays[localDate.dayOfWeek.value - 1]}"
}

fun iconForHomeRecord(record: Record): HomeRecordIcon {
    val content = record.content
    return when {
        "风" in content || "窗" in content -> HomeRecordIcon.Air
        "疲惫" in content || "困" in content -> HomeRecordIcon.Rest
        "呼吸" in content -> HomeRecordIcon.Breath
        "心跳" in content || "胸" in content -> HomeRecordIcon.Heart
        else -> HomeRecordIcon.Reflection
    }
}
