package com.aiawareness.diary.ui.screens

import android.net.Uri
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.aiawareness.diary.data.local.RecordPhotoStorage
import com.aiawareness.diary.data.model.Diary
import com.aiawareness.diary.data.model.Record
import com.aiawareness.diary.data.model.UserSettings
import com.aiawareness.diary.data.remote.OpenAIApiService
import com.aiawareness.diary.data.remote.OpenAIRequest
import com.aiawareness.diary.data.remote.OpenAIApiServiceFactory
import com.aiawareness.diary.data.remote.buildApiFailureMessage
import com.aiawareness.diary.data.remote.buildExceptionMessage
import com.aiawareness.diary.data.remote.safeLogError
import com.aiawareness.diary.data.repository.DiaryRepository
import com.aiawareness.diary.data.repository.RecordRepository
import com.aiawareness.diary.data.repository.SettingsRepository
import com.aiawareness.diary.domain.AiDiaryAutoGenerationCoordinator
import com.aiawareness.diary.domain.AiDiaryGenerationScheduler
import com.aiawareness.diary.util.DateUtil
import com.aiawareness.diary.util.PromptBuilder
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.io.File
import java.time.LocalDate
import javax.inject.Inject

data class MainUiState(
    val currentDate: String = DateUtil.getCurrentDate(),
    val currentMonth: Int = LocalDate.now().monthValue,
    val currentYear: Int = LocalDate.now().year,
    val records: List<Record> = emptyList(),
    val diary: Diary? = null,
    val datesWithRecords: Set<String> = emptySet(),
    val userSettings: UserSettings = UserSettings(),
    val hasApiKey: Boolean = false,
    val isLoading: Boolean = false,
    val error: String? = null,
    val autoDiaryGenerationHint: String? = null,
    val generatedDiaryReadyDate: String? = null,
    val isGeneratingDiary: Boolean = false,
    val pendingPhotoUri: Uri? = null,
    val pendingCapturedPhotoFile: File? = null,
    val pendingPhotoSource: PendingPhotoSource? = null
)

enum class PendingPhotoSource { Imported, Captured }

@HiltViewModel
class MainViewModel @Inject constructor(
    private val recordRepository: RecordRepository,
    private val diaryRepository: DiaryRepository,
    private val settingsRepository: SettingsRepository,
    private val apiServiceFactory: OpenAIApiServiceFactory,
    private val photoStorage: RecordPhotoStorage,
    private val autoGenerationCoordinator: AiDiaryAutoGenerationCoordinator,
    private val aiDiaryGenerationScheduler: AiDiaryGenerationScheduler
) : ViewModel() {

    private val _uiState = MutableStateFlow(MainUiState())
    val uiState: StateFlow<MainUiState> = _uiState.asStateFlow()
    private var pendingPhotoRequestToken: Long = 0L

    init {
        loadUserSettings()
        loadRecordsForDate(DateUtil.getCurrentDate())
        loadDatesWithRecords()
        catchUpAutoGeneratedDiaries()
    }

    fun loadRecordsForDate(date: String) {
        viewModelScope.launch {
            val records = recordRepository.getRecordsByDate(date)
            val diary = diaryRepository.getDiaryByDate(date)
            _uiState.update { it.copy(currentDate = date, records = records, diary = diary) }
        }
    }

    fun loadDatesWithRecords() {
        viewModelScope.launch {
            val dates = recordRepository.getDatesWithRecords()
            _uiState.update { it.copy(datesWithRecords = dates.toSet()) }
        }
    }

    fun saveRecord(content: String) {
        viewModelScope.launch {
            val pendingState = _uiState.value
            val trimmedContent = content.trim()
            val hasPendingPhoto = pendingState.pendingPhotoUri != null || pendingState.pendingCapturedPhotoFile != null

            if (trimmedContent.isBlank() && !hasPendingPhoto) {
                _uiState.update { it.copy(error = "记录内容不能为空") }
                return@launch
            }

            val currentDate = DateUtil.getCurrentDate()
            var photoPath = ""

            try {
                photoPath = when {
                    pendingState.pendingPhotoUri != null ->
                        photoStorage.persistImportedPhoto(pendingState.pendingPhotoUri)
                    pendingState.pendingCapturedPhotoFile != null ->
                        when (pendingState.pendingPhotoSource) {
                            PendingPhotoSource.Imported ->
                                photoStorage.persistStagedPhoto(pendingState.pendingCapturedPhotoFile)
                            else ->
                                photoStorage.persistStagedPhoto(pendingState.pendingCapturedPhotoFile)
                        }
                    else -> ""
                }
                val record = Record(
                    date = currentDate,
                    time = DateUtil.getCurrentTime(),
                    content = trimmedContent,
                    photoPath = photoPath
                )
                recordRepository.insertRecord(record)
                clearPendingPhotoState()
                _uiState.update { it.copy(error = null) }
                loadRecordsForDate(currentDate)
                loadDatesWithRecords()
            } catch (e: Exception) {
                cleanupNewPhotoIfNeeded(photoPath)
                _uiState.update { it.copy(error = buildExceptionMessage("保存记录失败", e)) }
            }
        }
    }

    fun deleteRecord(id: Long) {
        viewModelScope.launch {
            val deletedRecord = recordRepository.deleteRecordAndReturn(id)
            if (deletedRecord != null) {
                photoStorage.deletePhoto(deletedRecord.photoPath)
            }
            loadRecordsForDate(_uiState.value.currentDate)
            loadDatesWithRecords()
        }
    }

    fun updateRecord(record: Record) {
        viewModelScope.launch {
            recordRepository.updateRecord(record.copy(updatedAt = System.currentTimeMillis()))
            loadRecordsForDate(record.date)
            loadDatesWithRecords()
        }
    }

    fun restoreRecord(record: Record) {
        viewModelScope.launch {
            recordRepository.insertRecord(record)
            loadRecordsForDate(record.date)
            loadDatesWithRecords()
        }
    }

    fun setPendingPhoto(uri: Uri?) {
        nextPendingPhotoRequestToken()
        cleanupPendingCapturedPhotoIfReplaced()
        _uiState.update {
            it.copy(
                pendingPhotoUri = uri,
                pendingCapturedPhotoFile = null,
                pendingPhotoSource = if (uri != null) PendingPhotoSource.Imported else null
            )
        }
    }

    fun importPendingPhoto(uri: Uri) {
        val requestToken = nextPendingPhotoRequestToken()
        viewModelScope.launch {
            try {
                val tempFile = photoStorage.stageImportedPhoto(uri)
                handlePendingPhotoImportResult(requestToken, Result.success(tempFile))
            } catch (e: Exception) {
                handlePendingPhotoImportResult(requestToken, Result.failure(e))
            }
        }
    }

    fun setPendingCapturedPhoto(
        tempFile: File?,
        source: PendingPhotoSource = PendingPhotoSource.Captured
    ) {
        nextPendingPhotoRequestToken()
        cleanupPendingCapturedPhotoIfReplaced(nextCapturedPhotoFile = tempFile)
        _uiState.update {
            it.copy(
                pendingPhotoUri = null,
                pendingCapturedPhotoFile = tempFile,
                pendingPhotoSource = tempFile?.let { source }
            )
        }
    }

    fun createPendingCameraTempFileOrNull(): File? = runCatching {
        photoStorage.createCameraTempFile()
    }.getOrNull()

    fun replaceRecordPhoto(record: Record, uri: Uri) {
        viewModelScope.launch {
            var newPhotoPath = ""

            try {
                newPhotoPath = photoStorage.persistImportedPhoto(uri)
                val updatedRecord = record.copy(
                    photoPath = newPhotoPath,
                    updatedAt = System.currentTimeMillis()
                )
                recordRepository.updateRecord(updatedRecord)
                photoStorage.deletePhoto(record.photoPath)
                _uiState.update { it.copy(error = null) }
                loadRecordsForDate(record.date)
            } catch (e: Exception) {
                cleanupNewPhotoIfNeeded(newPhotoPath)
                _uiState.update { it.copy(error = buildExceptionMessage("更新记录照片失败", e)) }
            }
        }
    }

    private fun clearPendingPhotoState() {
        _uiState.value.pendingCapturedPhotoFile?.takeIf(File::exists)?.delete()
        _uiState.update { it.copy(pendingPhotoUri = null, pendingCapturedPhotoFile = null, pendingPhotoSource = null) }
    }

    private fun nextPendingPhotoRequestToken(): Long {
        pendingPhotoRequestToken += 1
        return pendingPhotoRequestToken
    }

    private fun handlePendingPhotoImportResult(requestToken: Long, result: Result<File>) {
        if (requestToken != pendingPhotoRequestToken) {
            result.getOrNull()?.takeIf(File::exists)?.delete()
            return
        }

        result.fold(
            onSuccess = { tempFile ->
                cleanupPendingCapturedPhotoIfReplaced(nextCapturedPhotoFile = tempFile)
                _uiState.update {
                    it.copy(
                        pendingPhotoUri = null,
                        pendingCapturedPhotoFile = tempFile,
                        pendingPhotoSource = PendingPhotoSource.Imported,
                        error = null
                    )
                }
            },
            onFailure = { error ->
                _uiState.update {
                    it.copy(
                        pendingPhotoUri = null,
                        pendingCapturedPhotoFile = null,
                        pendingPhotoSource = null,
                        error = buildExceptionMessage("读取照片失败", error)
                    )
                }
            }
        )
    }

    private fun cleanupPendingCapturedPhotoIfReplaced(nextCapturedPhotoFile: File? = null) {
        val currentCapturedPhotoFile = _uiState.value.pendingCapturedPhotoFile
        if (currentCapturedPhotoFile != null && currentCapturedPhotoFile != nextCapturedPhotoFile) {
            currentCapturedPhotoFile.takeIf(File::exists)?.delete()
        }
    }

    private fun cleanupNewPhotoIfNeeded(photoPath: String) {
        if (photoPath.isNotBlank()) {
            photoStorage.deletePhoto(photoPath)
        }
    }

    fun generateDiary() {
        viewModelScope.launch {
            val settings = _uiState.value.userSettings
            if (settings.apiEndpoint.isBlank() || settings.apiKey.isBlank() || settings.modelName.isBlank()) {
                _uiState.update { it.copy(error = "请先配置 API", isGeneratingDiary = false) }
                return@launch
            }

            val records = _uiState.value.records
            if (records.isEmpty()) {
                _uiState.update { it.copy(error = "没有记录可生成日记", isGeneratingDiary = false) }
                return@launch
            }

            _uiState.update { it.copy(isGeneratingDiary = true, error = null, generatedDiaryReadyDate = null) }
            val success = generateDiaryForDate(
                targetDate = _uiState.value.currentDate,
                records = records,
                settings = settings,
                updateVisibleState = true,
                showUiErrors = true
            )
            _uiState.update {
                it.copy(
                    isGeneratingDiary = false,
                    autoDiaryGenerationHint = if (success) null else it.autoDiaryGenerationHint
                )
            }
        }
    }

    private suspend fun generateDiaryForDate(
        targetDate: String,
        records: List<Record>,
        settings: UserSettings,
        updateVisibleState: Boolean,
        showUiErrors: Boolean
    ): Boolean {
        try {
            val apiService = apiServiceFactory.create(settings.apiEndpoint)
            val prompt = PromptBuilder.buildPrompt(
                nickname = settings.nickname,
                date = targetDate,
                records = records
            )
            val request = OpenAIRequest(
                model = settings.modelName,
                messages = listOf(
                    OpenAIRequest.Message("system", PromptBuilder.getSystemPrompt()),
                    OpenAIRequest.Message("user", prompt)
                ),
                temperature = PromptBuilder.DIARY_GENERATION_TEMPERATURE
            )
            val response = apiService.generateCompletion(
                authorization = "Bearer ${settings.apiKey}",
                request = request
            )

            if (response.isSuccessful && response.body() != null) {
                val content = response.body()!!.choices.firstOrNull()?.message?.content.orEmpty()
                val (diaryText, insightText) = PromptBuilder.parseAiResponse(content)
                val normalizedInsight = PromptBuilder.ensureInsightText(
                    records = records,
                    insight = insightText
                )
                diaryRepository.saveDiary(
                    Diary(
                        date = targetDate,
                        aiDiary = diaryText,
                        aiInsight = normalizedInsight
                    )
                )
                if (updateVisibleState) {
                    _uiState.update { it.copy(generatedDiaryReadyDate = targetDate) }
                    loadRecordsForDate(targetDate)
                }
                return true
            } else {
                val errorBody = response.errorBody()?.string()
                safeLogError("MainViewModel", "generateDiary failed: date=$targetDate code=${response.code()} body=$errorBody")
                if (showUiErrors) {
                    _uiState.update {
                        it.copy(error = buildApiFailureMessage(response.code(), errorBody))
                    }
                }
                return false
            }
        } catch (e: Exception) {
            safeLogError("MainViewModel", "generateDiary exception for $targetDate", e)
            if (showUiErrors) {
                _uiState.update { it.copy(error = buildExceptionMessage("生成失败", e)) }
            }
            return false
        }
    }

    private fun loadUserSettings() {
        viewModelScope.launch {
            settingsRepository.userSettings.collect { settings ->
                aiDiaryGenerationScheduler.scheduleDaily(
                    hour = settings.diaryGenerationHour,
                    minute = settings.diaryGenerationMinute
                )
                _uiState.update { it.copy(userSettings = settings) }
            }
        }

        viewModelScope.launch {
            settingsRepository.hasApiKey.collect { hasKey ->
                _uiState.update { it.copy(hasApiKey = hasKey) }
            }
        }
    }

    private fun catchUpAutoGeneratedDiaries() {
        viewModelScope.launch {
            _uiState.update { it.copy(autoDiaryGenerationHint = null) }
            val outcome = autoGenerationCoordinator.generateRecentMissingDiaries()
            _uiState.update {
                it.copy(
                    autoDiaryGenerationHint = homeAutoGenerationSnackbarHint(
                        catchUpGeneratedCount = outcome.generatedCount,
                        todayAutoGenerated = false,
                        autoGenerationFailed = outcome.failed
                    )
                )
            }
        }
    }

    fun updateMonth(year: Int, month: Int) {
        _uiState.update { it.copy(currentYear = year, currentMonth = month) }
    }

    fun clearError() {
        _uiState.update { it.copy(error = null) }
    }

    fun clearGeneratedDiaryReadyDate() {
        _uiState.update { it.copy(generatedDiaryReadyDate = null) }
    }

    fun clearAutoDiaryGenerationHint() {
        _uiState.update { it.copy(autoDiaryGenerationHint = null) }
    }

    internal fun beginPendingPhotoImportForTest(): Long = nextPendingPhotoRequestToken()

    internal fun completePendingPhotoImportForTest(requestToken: Long, result: Result<File>) {
        handlePendingPhotoImportResult(requestToken, result)
    }

    override fun onCleared() {
        clearPendingPhotoState()
        super.onCleared()
    }
}
